version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    volumes:
      - ./src:/usr/src/programma
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "8080:8888"
    volumes:
      - ./src:/usr/src/programma
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
